export interface StatBlock {
  name: string
  subtitle: string
  cr: string
  ac: number
  hp: string
  speed: string
  image?: string
  session: number
  stats: { label: string; score: number; mod: string }[]
  traits?: { name: string; desc: string }[]
  actions: { name: string; desc: string }[]
}

export const BESTIARY: StatBlock[] = [
  {
    name: 'Kael, Aprendiz de Thay',
    subtitle: 'Humanoide médio (humano), leal maligno',
    image: 'npcs/kael.png',
    session: 1,
    cr: '1',
    ac: 13,
    hp: '22 (5d8)',
    speed: '9m (6 casas)',
    stats: [
      { label: 'FOR', score: 9, mod: '-1' },
      { label: 'DES', score: 14, mod: '+2' },
      { label: 'CON', score: 12, mod: '+1' },
      { label: 'INT', score: 16, mod: '+3' },
      { label: 'SAB', score: 11, mod: '+0' },
      { label: 'CAR', score: 10, mod: '+0' },
    ],
    traits: [
      { name: 'Conjuração', desc: 'Kael conhece truques de necromancia e usa Raio de Enfraquecimento e Toque Chocante em combate.' },
    ],
    actions: [
      { name: 'Adaga', desc: '+4 para acertar, alcance 1,5/6m, um alvo. Acerto: 4 (1d4+2) de dano perfurante.' },
      { name: 'Raio de Enfraquecimento', desc: 'Ataque à distância de magia, +5 para acertar, alcance 36m. Acerto: 10 (3d6) de dano necrótico.' },
    ],
  },
  {
    name: 'Reth, Aprendiz de Thay',
    subtitle: 'Humanoide médio (humano), leal maligno',
    image: 'npcs/reth.png',
    session: 1,
    cr: '1',
    ac: 12,
    hp: '27 (6d8)',
    speed: '9m (6 casas)',
    stats: [
      { label: 'FOR', score: 8, mod: '-1' },
      { label: 'DES', score: 12, mod: '+1' },
      { label: 'CON', score: 13, mod: '+1' },
      { label: 'INT', score: 15, mod: '+2' },
      { label: 'SAB', score: 13, mod: '+1' },
      { label: 'CAR', score: 9, mod: '-1' },
    ],
    traits: [
      { name: 'Sangue Sacrificial', desc: 'Ao cair a 0 HP, Reth pode gastar sua reação para alimentar o poço de sangue negro, curando 10 HP do ritual em andamento.' },
    ],
    actions: [
      { name: 'Cajado', desc: '+3 para acertar, alcance 1,5m, um alvo. Acerto: 4 (1d6+1) de dano de concussão.' },
      { name: 'Mísseis Mágicos (3º nível)', desc: 'Três dardos de força automáticos, 3 (1d4+1) de dano cada.' },
    ],
  },
  {
    name: 'Valdris',
    subtitle: 'Humanoide médio (humano), leal maligno — vilão da Sessão 1',
    image: 'npcs/valdris.png',
    session: 1,
    cr: '6',
    ac: 15,
    hp: '85 (13d8+26)',
    speed: '9m (6 casas)',
    stats: [
      { label: 'FOR', score: 10, mod: '+0' },
      { label: 'DES', score: 14, mod: '+2' },
      { label: 'CON', score: 14, mod: '+2' },
      { label: 'INT', score: 19, mod: '+4' },
      { label: 'SAB', score: 13, mod: '+1' },
      { label: 'CAR', score: 15, mod: '+2' },
    ],
    traits: [
      { name: 'Mago Necromante Líder de Thay', desc: 'Frio, calculista, pragmático. Invocou o Dracolich Enfraquecido usando um poço de sangue negro alimentado pelo Coração de Vidro de Tiamat.' },
    ],
    actions: [
      { name: 'Multiataque', desc: 'Valdris conjura duas magias, ou faz um ataque com o cajado e conjura uma magia.' },
      { name: 'Cajado de Necromancia', desc: '+7 para acertar, alcance 1,5m. Acerto: 6 (1d8+2) de dano de concussão mais 9 (2d8) de dano necrótico.' },
      { name: 'Toque Vampírico (3º nível)', desc: 'Ataque corpo a corpo de magia, +8 para acertar. Acerto: 21 (6d6) de dano necrótico; Valdris recupera metade desse dano em PV.' },
    ],
  },
  {
    name: 'Carniçais',
    subtitle: 'Morto-vivo médio, caótico maligno',
    session: 1,
    cr: '1',
    ac: 12,
    hp: '22 (5d8)',
    speed: '9m (6 casas), escalada 9m (6 casas)',
    stats: [
      { label: 'FOR', score: 13, mod: '+1' },
      { label: 'DES', score: 15, mod: '+2' },
      { label: 'CON', score: 10, mod: '+0' },
      { label: 'INT', score: 7, mod: '-2' },
      { label: 'SAB', score: 10, mod: '+0' },
      { label: 'CAR', score: 6, mod: '-2' },
    ],
    traits: [
      { name: 'Imunidade a Morto-vivo', desc: 'Imune a veneno e às condições envenenado e exausto.' },
    ],
    actions: [
      { name: 'Mordida', desc: '+3 para acertar, alcance 1,5m. Acerto: 5 (2d4) de dano perfurante.' },
      { name: 'Garras', desc: '+3 para acertar, alcance 1,5m. Acerto: 5 (2d4) de dano cortante. Se o alvo não é morto-vivo, ele deve ser bem-sucedido numa TR de Constituição CD 10 ou fica Paralisado por 1 minuto (pode repetir a TR no fim de cada turno).' },
    ],
  },
  {
    name: 'Esqueletos',
    subtitle: 'Morto-vivo médio, leal maligno',
    session: 1,
    cr: '1/4',
    ac: 13,
    hp: '13 (2d8+4)',
    speed: '9m (6 casas)',
    stats: [
      { label: 'FOR', score: 10, mod: '+0' },
      { label: 'DES', score: 14, mod: '+2' },
      { label: 'CON', score: 15, mod: '+2' },
      { label: 'INT', score: 6, mod: '-2' },
      { label: 'SAB', score: 8, mod: '-1' },
      { label: 'CAR', score: 5, mod: '-3' },
    ],
    traits: [
      { name: 'Vulnerabilidade e Imunidade', desc: 'Vulnerável a dano de concussão. Imune a veneno e às condições envenenado e exausto.' },
    ],
    actions: [
      { name: 'Espada Curta', desc: '+4 para acertar, alcance 1,5m. Acerto: 5 (1d6+2) de dano perfurante.' },
      { name: 'Arco Curto', desc: '+4 para acertar à distância, alcance 24/96m. Acerto: 5 (1d6+2) de dano perfurante.' },
    ],
  },
  {
    name: 'Mímico',
    subtitle: 'Aberração média, neutro',
    session: 1,
    cr: '2',
    ac: 12,
    hp: '58 (9d8+18)',
    speed: '4,5m (3 casas)',
    stats: [
      { label: 'FOR', score: 17, mod: '+3' },
      { label: 'DES', score: 12, mod: '+1' },
      { label: 'CON', score: 15, mod: '+2' },
      { label: 'INT', score: 5, mod: '-3' },
      { label: 'SAB', score: 13, mod: '+1' },
      { label: 'CAR', score: 8, mod: '-1' },
    ],
    traits: [
      { name: 'Camuflagem', desc: 'Enquanto imóvel, o mímico parece um objeto inanimado (baú, porta, etc.). TR de Investigação/Percepção CD 15 pra perceber a farsa.' },
      { name: 'Aderência', desc: 'O mímico gruda em qualquer coisa que o toque. Uma criatura Agarrada dessa forma também fica Restringida até se soltar (TR de Força CD 13).' },
    ],
    actions: [
      { name: 'Pseudópode', desc: '+5 para acertar, alcance 1,5m. Acerto: 7 (1d8+3) de dano de concussão e o alvo é Agarrado (CD 13 pra escapar) se o mímico não estiver Agarrando outra criatura.' },
      { name: 'Mordida', desc: '+5 para acertar, alcance 1,5m, um alvo Agarrado. Acerto: 12 (2d8+3) de dano perfurante mais 4 (1d8) de dano ácido.' },
    ],
  },
  {
    name: 'Dracolich Enfraquecido',
    subtitle: 'Morto-vivo grande, leal maligno',
    image: 'npcs/dracolich.png',
    session: 1,
    cr: '8',
    ac: 17,
    hp: '150 (20d12+20)',
    speed: '9m (6 casas), voo 18m (12 casas)',
    stats: [
      { label: 'FOR', score: 21, mod: '+5' },
      { label: 'DES', score: 10, mod: '+0' },
      { label: 'CON', score: 19, mod: '+4' },
      { label: 'INT', score: 14, mod: '+2' },
      { label: 'SAB', score: 13, mod: '+1' },
      { label: 'CAR', score: 17, mod: '+3' },
    ],
    traits: [
      { name: 'Imunidade a Morto-vivo', desc: 'Imune a veneno e às condições envenenado, exausto e apavorado.' },
      { name: 'Forma Enfraquecida', desc: 'Invocado por um ritual incompleto com o Coração de Vidro de Tiamat — seu sopro e voo estão a metade do poder normal de um dracolich completo.' },
    ],
    actions: [
      { name: 'Mordida', desc: '+9 para acertar, alcance 3m, um alvo. Acerto: 17 (2d10+6) de dano perfurante.' },
      { name: 'Sopro Necrótico Enfraquecido (recarrega 5-6)', desc: 'Cone de 9m de energia necrótica. Cada criatura na área: TR de Constituição CD 15, 27 (6d8) de dano necrótico (metade se sucesso).' },
    ],
  },
  {
    name: 'Avatar of Death',
    subtitle: 'Aparição incorpórea, sem alinhamento — Portão do Primeiro Sussurro (reflavorado como um Phillipe de um multiverso onde Vecna venceu)',
    session: 2,
    cr: 'escala com quem invoca',
    ac: 20,
    hp: 'metade do PV máximo de quem o invocou',
    speed: '18m (voo, flutuando)',
    stats: [
      { label: 'FOR', score: 16, mod: '+3' },
      { label: 'DES', score: 16, mod: '+3' },
      { label: 'CON', score: 16, mod: '+3' },
      { label: 'INT', score: 16, mod: '+3' },
      { label: 'SAB', score: 16, mod: '+3' },
      { label: 'CAR', score: 16, mod: '+3' },
    ],
    traits: [
      { name: 'Movimento Incorpóreo', desc: 'Atravessa criaturas e objetos como terreno difícil; sofre dano se terminar o turno dentro de um objeto.' },
      { name: 'Alvo único', desc: 'Só ataca quem forçou a passagem sem dizer a senha certa — ignora todo o resto da cena. No combate, essa versão sombria do Phillipe implorava pra ele vencer Vecna de verdade.' },
    ],
    actions: [
      { name: 'Foice Ceifadora', desc: 'Acerta automaticamente, sem rolagem de ataque. 7 (1d8+3) cortante + 4 (1d8) necrótico por golpe.' },
    ],
  },
  {
    name: 'Water Weird',
    subtitle: 'Elemental médio, neutro — N3, emboscada na travessia',
    image: 'npcs/water_weird.png',
    session: 2,
    cr: '3',
    ac: 13,
    hp: '65 (10d10+10)',
    speed: '1,5m, natação 18m',
    stats: [
      { label: 'FOR', score: 16, mod: '+3' },
      { label: 'DES', score: 14, mod: '+2' },
      { label: 'CON', score: 13, mod: '+1' },
      { label: 'INT', score: 8, mod: '-1' },
      { label: 'SAB', score: 12, mod: '+1' },
      { label: 'CAR', score: 8, mod: '-1' },
    ],
    traits: [
      { name: 'Water Bound', desc: 'Morre se sair da água à qual está ligada, ou se essa água for destruída. Invisível enquanto totalmente submersa.' },
    ],
    actions: [
      { name: 'Surge', desc: '+5 para acertar, alcance 3m. Acerto: 13 (3d6+3) frio; alvo Médio ou menor fica Agarrado e Restringido.' },
    ],
  },
  {
    name: 'Ogre Zombie',
    subtitle: 'Morto-vivo grande, neutro maligno — N10, grupo de zumbis maiores comandados pelo Wight',
    image: 'npcs/ogre_zombie.png',
    session: 2,
    cr: '2',
    ac: 8,
    hp: '85 (9d10+36)',
    speed: '9m',
    stats: [
      { label: 'FOR', score: 19, mod: '+4' },
      { label: 'DES', score: 6, mod: '-2' },
      { label: 'CON', score: 18, mod: '+4' },
      { label: 'INT', score: 3, mod: '-4' },
      { label: 'SAB', score: 6, mod: '-2' },
      { label: 'CAR', score: 5, mod: '-3' },
    ],
    traits: [
      { name: 'Undead Fortitude', desc: 'Ao cair a 0 PV por dano não-crítico e não-radiante, pode fazer um TR de Constituição pra ficar com 1 PV em vez de cair.' },
    ],
    actions: [
      { name: 'Slam', desc: '+6 para acertar, alcance 1,5m. Acerto: 13 (2d8+4) de dano de concussão.' },
    ],
  },
  {
    name: 'Wight',
    subtitle: 'Morto-vivo médio, leal maligno — N10, comandante dos Ogre Zombies',
    session: 2,
    cr: '3',
    ac: 14,
    hp: '82 (11d8+33)',
    speed: '9m',
    stats: [
      { label: 'FOR', score: 15, mod: '+2' },
      { label: 'DES', score: 14, mod: '+2' },
      { label: 'CON', score: 16, mod: '+3' },
      { label: 'INT', score: 10, mod: '+0' },
      { label: 'SAB', score: 13, mod: '+1' },
      { label: 'CAR', score: 15, mod: '+2' },
    ],
    traits: [
      { name: 'Sensibilidade à Luz do Sol', desc: 'Sob luz solar direta, desvantagem em testes de habilidade e ataques.' },
      { name: 'Dreno de Vida', desc: 'TR Constituição CD 13: falha causa 6 (1d8+2) necrótico e reduz o PV máximo do alvo no mesmo tanto. Humanoide morto assim vira Zumbi sob controle do Wight.' },
    ],
    actions: [
      { name: 'Espada Necrótica', desc: '+4 para acertar, alcance 1,5m. Acerto: 6 (1d8+2) cortante + 4 (1d8) necrótico.' },
      { name: 'Arco Necrótico', desc: '+4 para acertar à distância. Acerto: 6 (1d8+2) perfurante + 4 (1d8) necrótico.' },
    ],
  },
  {
    name: 'Flesh Golem',
    subtitle: 'Construto médio, sem alinhamento — N10, costurado a partir de vítimas anteriores',
    session: 2,
    cr: '5',
    ac: 9,
    hp: '127 (15d8+60)',
    speed: '9m',
    stats: [
      { label: 'FOR', score: 19, mod: '+4' },
      { label: 'DES', score: 9, mod: '-1' },
      { label: 'CON', score: 18, mod: '+4' },
      { label: 'INT', score: 6, mod: '-2' },
      { label: 'SAB', score: 10, mod: '+0' },
      { label: 'CAR', score: 5, mod: '-3' },
    ],
    traits: [
      { name: 'Aversão ao Fogo', desc: 'Dano de fogo causa desvantagem nos ataques/testes dele até o fim do próximo turno.' },
      { name: 'Enfurecido', desc: 'Com PV pela metade ou menos no início do turno, pode entrar em fúria e atacar a criatura mais próxima — aliado ou não.' },
    ],
    actions: [
      { name: 'Golpe (2x por turno)', desc: '+7 para acertar, alcance 1,5m. Acerto: 13 (2d8+4) concussão + 4 (1d8) elétrico.' },
    ],
  },
  {
    name: 'Helmed Horror',
    subtitle: 'Construto médio, leal neutro — N10, guardião do santuário profanado',
    image: 'npcs/helmed_horror.png',
    session: 2,
    cr: '4',
    ac: 20,
    hp: '67 (9d8+27)',
    speed: '9m, voo 9m',
    stats: [
      { label: 'FOR', score: 18, mod: '+4' },
      { label: 'DES', score: 10, mod: '+0' },
      { label: 'CON', score: 16, mod: '+3' },
      { label: 'INT', score: 10, mod: '+0' },
      { label: 'SAB', score: 12, mod: '+1' },
      { label: 'CAR', score: 10, mod: '+0' },
    ],
    traits: [
      { name: 'Resistência Mágica', desc: 'Vantagem em testes de resistência contra magias e outros efeitos mágicos.' },
      { name: 'Imunidade a Magias', desc: 'Imune a três magias escolhidas por quem o criou. Nesta sessão: Rajada Mística/Eldritch Blast, Mísseis Mágicos e Aquecer Metal (confirmar essa última).' },
    ],
    actions: [
      { name: 'Espada Arcana (2x por turno)', desc: '+6 para acertar, alcance 1,5m. Acerto: 8 (1d8+4) cortante + 5 (1d10) força.' },
    ],
  },
  {
    name: 'Animated Armor',
    subtitle: 'Construto médio, sem alinhamento — N10, trio de armaduras guardiãs do santuário',
    image: 'npcs/animated_armor.png',
    session: 2,
    cr: '1',
    ac: 18,
    hp: '33 (6d8+6)',
    speed: '7,5m',
    stats: [
      { label: 'FOR', score: 14, mod: '+2' },
      { label: 'DES', score: 11, mod: '+0' },
      { label: 'CON', score: 13, mod: '+1' },
      { label: 'INT', score: 1, mod: '-5' },
      { label: 'SAB', score: 3, mod: '-4' },
      { label: 'CAR', score: 1, mod: '-5' },
    ],
    traits: [
      { name: 'Visão às Cegas', desc: '18m de alcance; além disso, é efetivamente cego.' },
    ],
    actions: [
      { name: 'Golpe (2x por turno)', desc: '+4 para acertar, alcance 1,5m. Acerto: 5 (1d6+2) de dano de concussão.' },
    ],
  },
  {
    name: 'Banshee',
    subtitle: 'Morto-vivo médio, caótico maligno — N10, "a Cantora Silenciada" que dá nome à sala',
    session: 2,
    cr: '4',
    ac: 12,
    hp: '54 (12d8)',
    speed: '1,5m, voo 12m',
    stats: [
      { label: 'FOR', score: 1, mod: '-5' },
      { label: 'DES', score: 14, mod: '+2' },
      { label: 'CON', score: 10, mod: '+0' },
      { label: 'INT', score: 12, mod: '+1' },
      { label: 'SAB', score: 11, mod: '+0' },
      { label: 'CAR', score: 17, mod: '+3' },
    ],
    traits: [
      { name: 'Movimento Incorpóreo', desc: 'Atravessa criaturas/objetos como terreno difícil.' },
      { name: 'Horrorizar', desc: 'TR Sabedoria CD 13 pra quem a veja: falha = Amedrontado.' },
    ],
    actions: [
      { name: 'Toque Corruptor', desc: '+5 para acertar, alcance 1,5m. Acerto: 7 (1d8+3) necrótico.' },
      { name: 'Grito Mortal / Wail (1x/dia)', desc: 'TR Constituição CD 13 pra todos num raio de 9m: falha com PV ≤25 = 0 PV direto; falha com PV maior = 10 (3d6) psíquico.' },
    ],
  },
  {
    name: 'Beholder Zombie',
    subtitle: 'Morto-vivo grande, sem alinhamento — o mesmo que matou Heidan Forteluz anos atrás, emboscou o grupo no N10',
    image: 'npcs/beholder_zombie.png',
    session: 2,
    cr: '5',
    ac: 15,
    hp: '93 (11d10+33)',
    speed: '1,5m, voo 6m (flutuando)',
    stats: [
      { label: 'FOR', score: 10, mod: '+0' },
      { label: 'DES', score: 6, mod: '-2' },
      { label: 'CON', score: 17, mod: '+3' },
      { label: 'INT', score: 3, mod: '-4' },
      { label: 'SAB', score: 12, mod: '+1' },
      { label: 'CAR', score: 5, mod: '-3' },
    ],
    traits: [
      { name: 'CD 17 nos Eye Rays', desc: 'Regra de mesa: a Classe de Dificuldade dos raios oculares escala com a contagem de mortes acumuladas na masmorra — chegou a CD 17 nesta sessão, acima do CD 14 padrão do stat block.' },
    ],
    actions: [
      { name: 'Bite', desc: '+5 para acertar, alcance 1,5m. Acerto: 16 (4d6+2) perfurante.' },
      { name: 'Eye Rays (2x por turno, 1d4)', desc: '1. Paralyzing Ray (paralisado); 2. Fear Ray (3d8 psíquico + amedrontado); 3. Enervation Ray (3d6 necrótico + Envenenado); 4. Disintegration Ray (5d10 força, desintegra a 0 PV).' },
    ],
  },
  {
    name: 'Shadow',
    subtitle: 'Morto-vivo médio, caótico maligno — N10, nasceram quando o ritual do santuário se completou (2 por PJ, 8 no total)',
    image: 'npcs/shadow.png',
    session: 2,
    cr: '1/2',
    ac: 12,
    hp: '27 (5d8+5)',
    speed: '12m',
    stats: [
      { label: 'FOR', score: 6, mod: '-2' },
      { label: 'DES', score: 14, mod: '+2' },
      { label: 'CON', score: 13, mod: '+1' },
      { label: 'INT', score: 6, mod: '-2' },
      { label: 'SAB', score: 10, mod: '+0' },
      { label: 'CAR', score: 8, mod: '-1' },
    ],
    traits: [
      { name: 'Furtividade nas Sombras', desc: 'Em penumbra/escuridão, pode usar Esconder-se como ação bônus.' },
    ],
    actions: [
      { name: 'Golpe Drenante', desc: '+4 para acertar, alcance 1,5m. Acerto: 5 (1d6+2) necrótico; reduz a Força do alvo em 1d4 (cumulativo).' },
    ],
  },
]
